// flow-typed signature: f8ae0ac9cb5c38dca7b740ec9a5f7aef
// flow-typed version: <<STUB>>/folktale_v^2.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'folktale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'folktale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'folktale/adt/index' {
  declare module.exports: any;
}

declare module 'folktale/adt/union/derivations/debug-representation' {
  declare module.exports: any;
}

declare module 'folktale/adt/union/derivations/equality' {
  declare module.exports: any;
}

declare module 'folktale/adt/union/derivations/index' {
  declare module.exports: any;
}

declare module 'folktale/adt/union/derivations/serialization' {
  declare module.exports: any;
}

declare module 'folktale/adt/union/index' {
  declare module.exports: any;
}

declare module 'folktale/adt/union/union' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/union/derivations/debug-representation' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/union/derivations/equality' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/union/derivations/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/union/derivations/serialization' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/union/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/adt/union/union' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/future/_deferred' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/future/_execution-state' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/future/_future' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/future/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/_task-execution' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/_task' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/do' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/task' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/wait-all' {
  declare module.exports: any;
}

declare module 'folktale/annotated/concurrency/task/wait-any' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/future-to-promise' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/maybe-to-result' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/maybe-to-validation' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/nodeback-to-task' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/nullable-to-maybe' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/nullable-to-result' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/nullable-to-validation' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/promise-to-future' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/promised-to-task' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/result-to-maybe' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/result-to-validation' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/validation-to-maybe' {
  declare module.exports: any;
}

declare module 'folktale/annotated/conversions/validation-to-result' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/lambda/compose' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/lambda/constant' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/lambda/curry' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/lambda/identity' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/lambda/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/lambda/partialize' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/object/from-pairs' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/object/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/object/map-entries' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/object/map-values' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/object/to-pairs' {
  declare module.exports: any;
}

declare module 'folktale/annotated/core/object/values' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/apply' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/bimap' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/chain' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/concat' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/curried' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/empty' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/equals' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/infix' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/map' {
  declare module.exports: any;
}

declare module 'folktale/annotated/fantasy-land/of' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/assert-function' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/assert-type' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/copy-documentation' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/defer' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/define-adt-methods' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/define' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/extend' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/fantasy-land' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/provide-fantasy-land-aliases' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/thunk' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/unsupported-method' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/warn-deprecated-method' {
  declare module.exports: any;
}

declare module 'folktale/annotated/helpers/warn-deprecation' {
  declare module.exports: any;
}

declare module 'folktale/annotated/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/maybe/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/maybe/maybe' {
  declare module.exports: any;
}

declare module 'folktale/annotated/result/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/result/result' {
  declare module.exports: any;
}

declare module 'folktale/annotated/result/try' {
  declare module.exports: any;
}

declare module 'folktale/annotated/validation/collect' {
  declare module.exports: any;
}

declare module 'folktale/annotated/validation/index' {
  declare module.exports: any;
}

declare module 'folktale/annotated/validation/validation' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/future/_deferred' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/future/_execution-state' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/future/_future' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/future/index' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/index' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/_task-execution' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/_task' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/do' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/index' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/task' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/wait-all' {
  declare module.exports: any;
}

declare module 'folktale/concurrency/task/wait-any' {
  declare module.exports: any;
}

declare module 'folktale/conversions/future-to-promise' {
  declare module.exports: any;
}

declare module 'folktale/conversions/index' {
  declare module.exports: any;
}

declare module 'folktale/conversions/maybe-to-result' {
  declare module.exports: any;
}

declare module 'folktale/conversions/maybe-to-validation' {
  declare module.exports: any;
}

declare module 'folktale/conversions/nodeback-to-task' {
  declare module.exports: any;
}

declare module 'folktale/conversions/nullable-to-maybe' {
  declare module.exports: any;
}

declare module 'folktale/conversions/nullable-to-result' {
  declare module.exports: any;
}

declare module 'folktale/conversions/nullable-to-validation' {
  declare module.exports: any;
}

declare module 'folktale/conversions/promise-to-future' {
  declare module.exports: any;
}

declare module 'folktale/conversions/promised-to-task' {
  declare module.exports: any;
}

declare module 'folktale/conversions/result-to-maybe' {
  declare module.exports: any;
}

declare module 'folktale/conversions/result-to-validation' {
  declare module.exports: any;
}

declare module 'folktale/conversions/validation-to-maybe' {
  declare module.exports: any;
}

declare module 'folktale/conversions/validation-to-result' {
  declare module.exports: any;
}

declare module 'folktale/core/index' {
  declare module.exports: any;
}

declare module 'folktale/core/lambda/compose' {
  declare module.exports: any;
}

declare module 'folktale/core/lambda/constant' {
  declare module.exports: any;
}

declare module 'folktale/core/lambda/curry' {
  declare module.exports: any;
}

declare module 'folktale/core/lambda/identity' {
  declare module.exports: any;
}

declare module 'folktale/core/lambda/index' {
  declare module.exports: any;
}

declare module 'folktale/core/lambda/partialize' {
  declare module.exports: any;
}

declare module 'folktale/core/object/from-pairs' {
  declare module.exports: any;
}

declare module 'folktale/core/object/index' {
  declare module.exports: any;
}

declare module 'folktale/core/object/map-entries' {
  declare module.exports: any;
}

declare module 'folktale/core/object/map-values' {
  declare module.exports: any;
}

declare module 'folktale/core/object/to-pairs' {
  declare module.exports: any;
}

declare module 'folktale/core/object/values' {
  declare module.exports: any;
}

declare module 'folktale/dist/umd/folktale' {
  declare module.exports: any;
}

declare module 'folktale/dist/umd/folktale.min' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/apply' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/bimap' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/chain' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/concat' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/curried' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/empty' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/equals' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/index' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/infix' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/map' {
  declare module.exports: any;
}

declare module 'folktale/fantasy-land/of' {
  declare module.exports: any;
}

declare module 'folktale/helpers/assert-function' {
  declare module.exports: any;
}

declare module 'folktale/helpers/assert-type' {
  declare module.exports: any;
}

declare module 'folktale/helpers/copy-documentation' {
  declare module.exports: any;
}

declare module 'folktale/helpers/defer' {
  declare module.exports: any;
}

declare module 'folktale/helpers/define-adt-methods' {
  declare module.exports: any;
}

declare module 'folktale/helpers/define' {
  declare module.exports: any;
}

declare module 'folktale/helpers/extend' {
  declare module.exports: any;
}

declare module 'folktale/helpers/fantasy-land' {
  declare module.exports: any;
}

declare module 'folktale/helpers/provide-fantasy-land-aliases' {
  declare module.exports: any;
}

declare module 'folktale/helpers/thunk' {
  declare module.exports: any;
}

declare module 'folktale/helpers/unsupported-method' {
  declare module.exports: any;
}

declare module 'folktale/helpers/warn-deprecated-method' {
  declare module.exports: any;
}

declare module 'folktale/helpers/warn-deprecation' {
  declare module.exports: any;
}

declare module 'folktale/maybe/index' {
  declare module.exports: any;
}

declare module 'folktale/maybe/maybe' {
  declare module.exports: any;
}

declare module 'folktale/result/index' {
  declare module.exports: any;
}

declare module 'folktale/result/result' {
  declare module.exports: any;
}

declare module 'folktale/result/try' {
  declare module.exports: any;
}

declare module 'folktale/validation/collect' {
  declare module.exports: any;
}

declare module 'folktale/validation/index' {
  declare module.exports: any;
}

declare module 'folktale/validation/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'folktale/adt/index.js' {
  declare module.exports: $Exports<'folktale/adt/index'>;
}
declare module 'folktale/adt/union/derivations/debug-representation.js' {
  declare module.exports: $Exports<'folktale/adt/union/derivations/debug-representation'>;
}
declare module 'folktale/adt/union/derivations/equality.js' {
  declare module.exports: $Exports<'folktale/adt/union/derivations/equality'>;
}
declare module 'folktale/adt/union/derivations/index.js' {
  declare module.exports: $Exports<'folktale/adt/union/derivations/index'>;
}
declare module 'folktale/adt/union/derivations/serialization.js' {
  declare module.exports: $Exports<'folktale/adt/union/derivations/serialization'>;
}
declare module 'folktale/adt/union/index.js' {
  declare module.exports: $Exports<'folktale/adt/union/index'>;
}
declare module 'folktale/adt/union/union.js' {
  declare module.exports: $Exports<'folktale/adt/union/union'>;
}
declare module 'folktale/annotated/adt/index.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/index'>;
}
declare module 'folktale/annotated/adt/union/derivations/debug-representation.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/union/derivations/debug-representation'>;
}
declare module 'folktale/annotated/adt/union/derivations/equality.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/union/derivations/equality'>;
}
declare module 'folktale/annotated/adt/union/derivations/index.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/union/derivations/index'>;
}
declare module 'folktale/annotated/adt/union/derivations/serialization.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/union/derivations/serialization'>;
}
declare module 'folktale/annotated/adt/union/index.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/union/index'>;
}
declare module 'folktale/annotated/adt/union/union.js' {
  declare module.exports: $Exports<'folktale/annotated/adt/union/union'>;
}
declare module 'folktale/annotated/concurrency/future/_deferred.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/future/_deferred'>;
}
declare module 'folktale/annotated/concurrency/future/_execution-state.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/future/_execution-state'>;
}
declare module 'folktale/annotated/concurrency/future/_future.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/future/_future'>;
}
declare module 'folktale/annotated/concurrency/future/index.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/future/index'>;
}
declare module 'folktale/annotated/concurrency/index.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/index'>;
}
declare module 'folktale/annotated/concurrency/task/_task-execution.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/_task-execution'>;
}
declare module 'folktale/annotated/concurrency/task/_task.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/_task'>;
}
declare module 'folktale/annotated/concurrency/task/do.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/do'>;
}
declare module 'folktale/annotated/concurrency/task/index.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/index'>;
}
declare module 'folktale/annotated/concurrency/task/task.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/task'>;
}
declare module 'folktale/annotated/concurrency/task/wait-all.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/wait-all'>;
}
declare module 'folktale/annotated/concurrency/task/wait-any.js' {
  declare module.exports: $Exports<'folktale/annotated/concurrency/task/wait-any'>;
}
declare module 'folktale/annotated/conversions/future-to-promise.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/future-to-promise'>;
}
declare module 'folktale/annotated/conversions/index.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/index'>;
}
declare module 'folktale/annotated/conversions/maybe-to-result.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/maybe-to-result'>;
}
declare module 'folktale/annotated/conversions/maybe-to-validation.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/maybe-to-validation'>;
}
declare module 'folktale/annotated/conversions/nodeback-to-task.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/nodeback-to-task'>;
}
declare module 'folktale/annotated/conversions/nullable-to-maybe.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/nullable-to-maybe'>;
}
declare module 'folktale/annotated/conversions/nullable-to-result.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/nullable-to-result'>;
}
declare module 'folktale/annotated/conversions/nullable-to-validation.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/nullable-to-validation'>;
}
declare module 'folktale/annotated/conversions/promise-to-future.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/promise-to-future'>;
}
declare module 'folktale/annotated/conversions/promised-to-task.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/promised-to-task'>;
}
declare module 'folktale/annotated/conversions/result-to-maybe.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/result-to-maybe'>;
}
declare module 'folktale/annotated/conversions/result-to-validation.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/result-to-validation'>;
}
declare module 'folktale/annotated/conversions/validation-to-maybe.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/validation-to-maybe'>;
}
declare module 'folktale/annotated/conversions/validation-to-result.js' {
  declare module.exports: $Exports<'folktale/annotated/conversions/validation-to-result'>;
}
declare module 'folktale/annotated/core/index.js' {
  declare module.exports: $Exports<'folktale/annotated/core/index'>;
}
declare module 'folktale/annotated/core/lambda/compose.js' {
  declare module.exports: $Exports<'folktale/annotated/core/lambda/compose'>;
}
declare module 'folktale/annotated/core/lambda/constant.js' {
  declare module.exports: $Exports<'folktale/annotated/core/lambda/constant'>;
}
declare module 'folktale/annotated/core/lambda/curry.js' {
  declare module.exports: $Exports<'folktale/annotated/core/lambda/curry'>;
}
declare module 'folktale/annotated/core/lambda/identity.js' {
  declare module.exports: $Exports<'folktale/annotated/core/lambda/identity'>;
}
declare module 'folktale/annotated/core/lambda/index.js' {
  declare module.exports: $Exports<'folktale/annotated/core/lambda/index'>;
}
declare module 'folktale/annotated/core/lambda/partialize.js' {
  declare module.exports: $Exports<'folktale/annotated/core/lambda/partialize'>;
}
declare module 'folktale/annotated/core/object/from-pairs.js' {
  declare module.exports: $Exports<'folktale/annotated/core/object/from-pairs'>;
}
declare module 'folktale/annotated/core/object/index.js' {
  declare module.exports: $Exports<'folktale/annotated/core/object/index'>;
}
declare module 'folktale/annotated/core/object/map-entries.js' {
  declare module.exports: $Exports<'folktale/annotated/core/object/map-entries'>;
}
declare module 'folktale/annotated/core/object/map-values.js' {
  declare module.exports: $Exports<'folktale/annotated/core/object/map-values'>;
}
declare module 'folktale/annotated/core/object/to-pairs.js' {
  declare module.exports: $Exports<'folktale/annotated/core/object/to-pairs'>;
}
declare module 'folktale/annotated/core/object/values.js' {
  declare module.exports: $Exports<'folktale/annotated/core/object/values'>;
}
declare module 'folktale/annotated/fantasy-land/apply.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/apply'>;
}
declare module 'folktale/annotated/fantasy-land/bimap.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/bimap'>;
}
declare module 'folktale/annotated/fantasy-land/chain.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/chain'>;
}
declare module 'folktale/annotated/fantasy-land/concat.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/concat'>;
}
declare module 'folktale/annotated/fantasy-land/curried.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/curried'>;
}
declare module 'folktale/annotated/fantasy-land/empty.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/empty'>;
}
declare module 'folktale/annotated/fantasy-land/equals.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/equals'>;
}
declare module 'folktale/annotated/fantasy-land/index.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/index'>;
}
declare module 'folktale/annotated/fantasy-land/infix.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/infix'>;
}
declare module 'folktale/annotated/fantasy-land/map.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/map'>;
}
declare module 'folktale/annotated/fantasy-land/of.js' {
  declare module.exports: $Exports<'folktale/annotated/fantasy-land/of'>;
}
declare module 'folktale/annotated/helpers/assert-function.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/assert-function'>;
}
declare module 'folktale/annotated/helpers/assert-type.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/assert-type'>;
}
declare module 'folktale/annotated/helpers/copy-documentation.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/copy-documentation'>;
}
declare module 'folktale/annotated/helpers/defer.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/defer'>;
}
declare module 'folktale/annotated/helpers/define-adt-methods.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/define-adt-methods'>;
}
declare module 'folktale/annotated/helpers/define.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/define'>;
}
declare module 'folktale/annotated/helpers/extend.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/extend'>;
}
declare module 'folktale/annotated/helpers/fantasy-land.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/fantasy-land'>;
}
declare module 'folktale/annotated/helpers/provide-fantasy-land-aliases.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/provide-fantasy-land-aliases'>;
}
declare module 'folktale/annotated/helpers/thunk.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/thunk'>;
}
declare module 'folktale/annotated/helpers/unsupported-method.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/unsupported-method'>;
}
declare module 'folktale/annotated/helpers/warn-deprecated-method.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/warn-deprecated-method'>;
}
declare module 'folktale/annotated/helpers/warn-deprecation.js' {
  declare module.exports: $Exports<'folktale/annotated/helpers/warn-deprecation'>;
}
declare module 'folktale/annotated/index.js' {
  declare module.exports: $Exports<'folktale/annotated/index'>;
}
declare module 'folktale/annotated/maybe/index.js' {
  declare module.exports: $Exports<'folktale/annotated/maybe/index'>;
}
declare module 'folktale/annotated/maybe/maybe.js' {
  declare module.exports: $Exports<'folktale/annotated/maybe/maybe'>;
}
declare module 'folktale/annotated/result/index.js' {
  declare module.exports: $Exports<'folktale/annotated/result/index'>;
}
declare module 'folktale/annotated/result/result.js' {
  declare module.exports: $Exports<'folktale/annotated/result/result'>;
}
declare module 'folktale/annotated/result/try.js' {
  declare module.exports: $Exports<'folktale/annotated/result/try'>;
}
declare module 'folktale/annotated/validation/collect.js' {
  declare module.exports: $Exports<'folktale/annotated/validation/collect'>;
}
declare module 'folktale/annotated/validation/index.js' {
  declare module.exports: $Exports<'folktale/annotated/validation/index'>;
}
declare module 'folktale/annotated/validation/validation.js' {
  declare module.exports: $Exports<'folktale/annotated/validation/validation'>;
}
declare module 'folktale/concurrency/future/_deferred.js' {
  declare module.exports: $Exports<'folktale/concurrency/future/_deferred'>;
}
declare module 'folktale/concurrency/future/_execution-state.js' {
  declare module.exports: $Exports<'folktale/concurrency/future/_execution-state'>;
}
declare module 'folktale/concurrency/future/_future.js' {
  declare module.exports: $Exports<'folktale/concurrency/future/_future'>;
}
declare module 'folktale/concurrency/future/index.js' {
  declare module.exports: $Exports<'folktale/concurrency/future/index'>;
}
declare module 'folktale/concurrency/index.js' {
  declare module.exports: $Exports<'folktale/concurrency/index'>;
}
declare module 'folktale/concurrency/task/_task-execution.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/_task-execution'>;
}
declare module 'folktale/concurrency/task/_task.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/_task'>;
}
declare module 'folktale/concurrency/task/do.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/do'>;
}
declare module 'folktale/concurrency/task/index.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/index'>;
}
declare module 'folktale/concurrency/task/task.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/task'>;
}
declare module 'folktale/concurrency/task/wait-all.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/wait-all'>;
}
declare module 'folktale/concurrency/task/wait-any.js' {
  declare module.exports: $Exports<'folktale/concurrency/task/wait-any'>;
}
declare module 'folktale/conversions/future-to-promise.js' {
  declare module.exports: $Exports<'folktale/conversions/future-to-promise'>;
}
declare module 'folktale/conversions/index.js' {
  declare module.exports: $Exports<'folktale/conversions/index'>;
}
declare module 'folktale/conversions/maybe-to-result.js' {
  declare module.exports: $Exports<'folktale/conversions/maybe-to-result'>;
}
declare module 'folktale/conversions/maybe-to-validation.js' {
  declare module.exports: $Exports<'folktale/conversions/maybe-to-validation'>;
}
declare module 'folktale/conversions/nodeback-to-task.js' {
  declare module.exports: $Exports<'folktale/conversions/nodeback-to-task'>;
}
declare module 'folktale/conversions/nullable-to-maybe.js' {
  declare module.exports: $Exports<'folktale/conversions/nullable-to-maybe'>;
}
declare module 'folktale/conversions/nullable-to-result.js' {
  declare module.exports: $Exports<'folktale/conversions/nullable-to-result'>;
}
declare module 'folktale/conversions/nullable-to-validation.js' {
  declare module.exports: $Exports<'folktale/conversions/nullable-to-validation'>;
}
declare module 'folktale/conversions/promise-to-future.js' {
  declare module.exports: $Exports<'folktale/conversions/promise-to-future'>;
}
declare module 'folktale/conversions/promised-to-task.js' {
  declare module.exports: $Exports<'folktale/conversions/promised-to-task'>;
}
declare module 'folktale/conversions/result-to-maybe.js' {
  declare module.exports: $Exports<'folktale/conversions/result-to-maybe'>;
}
declare module 'folktale/conversions/result-to-validation.js' {
  declare module.exports: $Exports<'folktale/conversions/result-to-validation'>;
}
declare module 'folktale/conversions/validation-to-maybe.js' {
  declare module.exports: $Exports<'folktale/conversions/validation-to-maybe'>;
}
declare module 'folktale/conversions/validation-to-result.js' {
  declare module.exports: $Exports<'folktale/conversions/validation-to-result'>;
}
declare module 'folktale/core/index.js' {
  declare module.exports: $Exports<'folktale/core/index'>;
}
declare module 'folktale/core/lambda/compose.js' {
  declare module.exports: $Exports<'folktale/core/lambda/compose'>;
}
declare module 'folktale/core/lambda/constant.js' {
  declare module.exports: $Exports<'folktale/core/lambda/constant'>;
}
declare module 'folktale/core/lambda/curry.js' {
  declare module.exports: $Exports<'folktale/core/lambda/curry'>;
}
declare module 'folktale/core/lambda/identity.js' {
  declare module.exports: $Exports<'folktale/core/lambda/identity'>;
}
declare module 'folktale/core/lambda/index.js' {
  declare module.exports: $Exports<'folktale/core/lambda/index'>;
}
declare module 'folktale/core/lambda/partialize.js' {
  declare module.exports: $Exports<'folktale/core/lambda/partialize'>;
}
declare module 'folktale/core/object/from-pairs.js' {
  declare module.exports: $Exports<'folktale/core/object/from-pairs'>;
}
declare module 'folktale/core/object/index.js' {
  declare module.exports: $Exports<'folktale/core/object/index'>;
}
declare module 'folktale/core/object/map-entries.js' {
  declare module.exports: $Exports<'folktale/core/object/map-entries'>;
}
declare module 'folktale/core/object/map-values.js' {
  declare module.exports: $Exports<'folktale/core/object/map-values'>;
}
declare module 'folktale/core/object/to-pairs.js' {
  declare module.exports: $Exports<'folktale/core/object/to-pairs'>;
}
declare module 'folktale/core/object/values.js' {
  declare module.exports: $Exports<'folktale/core/object/values'>;
}
declare module 'folktale/dist/umd/folktale.js' {
  declare module.exports: $Exports<'folktale/dist/umd/folktale'>;
}
declare module 'folktale/dist/umd/folktale.min.js' {
  declare module.exports: $Exports<'folktale/dist/umd/folktale.min'>;
}
declare module 'folktale/fantasy-land/apply.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/apply'>;
}
declare module 'folktale/fantasy-land/bimap.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/bimap'>;
}
declare module 'folktale/fantasy-land/chain.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/chain'>;
}
declare module 'folktale/fantasy-land/concat.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/concat'>;
}
declare module 'folktale/fantasy-land/curried.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/curried'>;
}
declare module 'folktale/fantasy-land/empty.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/empty'>;
}
declare module 'folktale/fantasy-land/equals.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/equals'>;
}
declare module 'folktale/fantasy-land/index.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/index'>;
}
declare module 'folktale/fantasy-land/infix.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/infix'>;
}
declare module 'folktale/fantasy-land/map.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/map'>;
}
declare module 'folktale/fantasy-land/of.js' {
  declare module.exports: $Exports<'folktale/fantasy-land/of'>;
}
declare module 'folktale/helpers/assert-function.js' {
  declare module.exports: $Exports<'folktale/helpers/assert-function'>;
}
declare module 'folktale/helpers/assert-type.js' {
  declare module.exports: $Exports<'folktale/helpers/assert-type'>;
}
declare module 'folktale/helpers/copy-documentation.js' {
  declare module.exports: $Exports<'folktale/helpers/copy-documentation'>;
}
declare module 'folktale/helpers/defer.js' {
  declare module.exports: $Exports<'folktale/helpers/defer'>;
}
declare module 'folktale/helpers/define-adt-methods.js' {
  declare module.exports: $Exports<'folktale/helpers/define-adt-methods'>;
}
declare module 'folktale/helpers/define.js' {
  declare module.exports: $Exports<'folktale/helpers/define'>;
}
declare module 'folktale/helpers/extend.js' {
  declare module.exports: $Exports<'folktale/helpers/extend'>;
}
declare module 'folktale/helpers/fantasy-land.js' {
  declare module.exports: $Exports<'folktale/helpers/fantasy-land'>;
}
declare module 'folktale/helpers/provide-fantasy-land-aliases.js' {
  declare module.exports: $Exports<'folktale/helpers/provide-fantasy-land-aliases'>;
}
declare module 'folktale/helpers/thunk.js' {
  declare module.exports: $Exports<'folktale/helpers/thunk'>;
}
declare module 'folktale/helpers/unsupported-method.js' {
  declare module.exports: $Exports<'folktale/helpers/unsupported-method'>;
}
declare module 'folktale/helpers/warn-deprecated-method.js' {
  declare module.exports: $Exports<'folktale/helpers/warn-deprecated-method'>;
}
declare module 'folktale/helpers/warn-deprecation.js' {
  declare module.exports: $Exports<'folktale/helpers/warn-deprecation'>;
}
declare module 'folktale/index' {
  declare module.exports: $Exports<'folktale'>;
}
declare module 'folktale/index.js' {
  declare module.exports: $Exports<'folktale'>;
}
declare module 'folktale/maybe/index.js' {
  declare module.exports: $Exports<'folktale/maybe/index'>;
}
declare module 'folktale/maybe/maybe.js' {
  declare module.exports: $Exports<'folktale/maybe/maybe'>;
}
declare module 'folktale/result/index.js' {
  declare module.exports: $Exports<'folktale/result/index'>;
}
declare module 'folktale/result/result.js' {
  declare module.exports: $Exports<'folktale/result/result'>;
}
declare module 'folktale/result/try.js' {
  declare module.exports: $Exports<'folktale/result/try'>;
}
declare module 'folktale/validation/collect.js' {
  declare module.exports: $Exports<'folktale/validation/collect'>;
}
declare module 'folktale/validation/index.js' {
  declare module.exports: $Exports<'folktale/validation/index'>;
}
declare module 'folktale/validation/validation.js' {
  declare module.exports: $Exports<'folktale/validation/validation'>;
}
